### ISSUE TITLE
Download instructions for command line don't work

### ISSUE THREAD

**Issue by milanmajchrak** [dataquest-dev/DSpace#803]
Original issue: https://github.com/ufal/clarin-dspace/issues/1130

**Comment by Paurikova2** [comment]
We can download a bitstream from an item via the command line using the bitstream UUID: /api/core/bitstreams/{uuid}/content,
or using the handle and file name: /bitstreams/handle/{handle}/{filename}PDT-C-1.0.zip.
But what happens when an item has more than one bitstream?

- [x]  Can we download several bitstreams using /api/core/bitstreams/{id1,id2,id3}/content?
For multiple bitstream uuid only separated downloads:
curl -k -o bitstream1.zip https://dev-5.pc:8443/server/api/core/bitstreams/b5a24281-caf3-41a5-bab9-ece451422880/content
-o bitstream2.zip https://dev-5.pc:8443/server/api/core/bitstreams/5711aa79-5821-444a-9575-d8150d532a70/content

- [ ]  If it works, how is the link generated on the backend? It doesn't work

- [ ]  If it doesn't work, how can we use the existing ZIP service? - DOESN'T WORK

WorkflowItemRestRepository - findByItemUuid
Update: Works downloading as curl -k --remote-name-all [https://dev-5.pc:8443/server/api/core/bitstreams/handle/11234/1-5419/{file_name](https://dev-5.pc:8443/server/api/core/bitstreams/handle/11234/1-5419/%7Bfile_name), file_name}

Note: don't forget to use flag -k -> The -k flag in curl is used to disable SSL certificate verification. This flag allows curl to make requests to a server with an invalid or self-signed SSL certificate without throwing an error.
